### ISSUE TITLE
Are there any pypi package?

### ISSUE THREAD

**Issue by miratcan** [Prezzodaman/pymod#1]

**Comment by Prezzodaman** [comment]
I'll try and add Pymod to PyPI at some point. Right now, it's in desperate need of a rewrite - it isn't even a library as such, and the whole thing runs in a While loop! I've been working on an object-oriented version which lets you use the rendering routines in other Python code, so as soon as I complete it, I'll push it here and try and get it added :)

**Comment by DidierMalenfant** [comment]
Sorry I missed this issue when I filed mine.

This is currently being done as part of #3

**Comment by DidierMalenfant** [comment]
Package is published and can be found [here](https://pypi.org/project/pymod-amiga/).
