### ISSUE TITLE
"ode2ptk.mod" rendering channels 2, 3 and 4 offset

### ISSUE THREAD

**Issue by Prezzodaman** [Prezzodaman/pymod#11]
For some reason, when rendering "ode2ptk.mod" to individual channels, channels 2-4 render slightly later, even though it's using the exact same code as rendering to a mixed file. In the picture below, the black line shows where the other channels should start:

![image](https://github.com/Prezzodaman/pymod/assets/76560493/37170bd4-4828-4cfb-ab2f-b9de730c1692)

**Comment by DidierMalenfant** [comment]
I see channel 1 and 3 starting later here but when you play the module in PT2.3d the silence is there at the beginning for those two channels.

Maybe I'm missing something?

**Comment by Prezzodaman** [comment]
I think you might be. If you mix all the rendered channels together, render the module as one file, then invert those into each other, you can hear channels 2-4 play slightly after each other, while channel 1 is cancelled out.

**Comment by DidierMalenfant** [comment]
Oh I get what you mean now. I thought you meant 2-4 versus 1-3 but you mean comparing channel 2 and channel 4.

Let me see if I can repro here too.

**Comment by Prezzodaman** [comment]
Well, I meant channels 2, 3 and 4, but I'd be interested if you can reproduce this issue too!

**Comment by DidierMalenfant** [comment]
Comparing to PT2.3d renders, channel 2, 3,  and 4 are about 40ms late in pymod's version. Odd....

**Comment by Prezzodaman** [comment]
Fixed in commit https://github.com/Prezzodaman/pymod/commit/940b501eae858335378b10c112d7eed9d27a7981 - while adding the estimation feature, I reordered a majority of the code, and that seemed to fix it (the tempo calculations were likely in the wrong place). Now every single test passes!
