### ISSUE TITLE
Errors playing Professional Tracker by h0ffman

### ISSUE THREAD

**Issue by DidierMalenfant** [Prezzodaman/pymod#22]
Opening this as a reminder to look into this at some point...

There are errors playing [Professional Tracker](https://modarchive.org/index.php?request=view_by_moduleid&query=174955) by h0ffman.

Initial vocals are not at the correct speed but there might be other issues.

**Comment by Prezzodaman** [comment]
Fixed in commit https://github.com/Prezzodaman/pymod/commit/b57a8eda3fd322b36cd1283872922f9c090fbd70, it now plays perfectly the whole way through.
