### ISSUE TITLE
Creating a pip package and modularizing the code

### ISSUE THREAD

**Issue by DidierMalenfant** [Prezzodaman/pymod#3]
I'd like to make the lib into something that can be posted on pypi and that can be used both as a command line tool and a module.

Anything I should be aware of before embarking on this?

I use hatch to build my pypi packages, let me know if that works for you too.

I can provide a PR for this.

**Comment by Prezzodaman** [comment]
I seriously appreciate this! I started an object-oriented version that could be used as a library, and it mostly worked apart from Ode2ptk.mod, which completely refused to start. Really, the only key thing is that I was going to add a variable containing the buffer size for one line (ms per tick * speed) allowing for the command line display.

Another thing to consider is that, even though I know Python well enough, I don't know GitHub that well, and I'm clueless when it comes to packaging stuff, so please forgive me... I'd appreciate any help or advice regarding this :)

If so desired, I can try sharing the (very janky) object-oriented version that I started. It mostly works when rendering to files, but refuses to work with PyAudio for some reason.

**Comment by DidierMalenfant** [comment]
I'm going to wrap the code into a package, leaving it mostly untouched as to how it works internally, then we will do the unit tests #5 and then we'll circle back to this and start turning it into a module too.

It's not too complicated, and the result should be useable as command line or imported into another python project.

Here is an [example](https://pypi.org/project/TraktorBuddy/) of a lib I did that works that way.

**Comment by DidierMalenfant** [comment]
Ok... first pass is provided as PR #6 

Load more can be done but let's leave this open, merge if the PR is ok with you, and I'll move to unit tests to make sure nothing is getting broken in the process.

**Comment by DidierMalenfant** [comment]
PR #9 has some tweaks to the module API. Baring any issues this should be ready to post on pypi once you have an account there.

You can install [hatch](https://hatch.pypa.io) and do:
```console
hatch build
hatch publish
```

and that will make the module easily available to everyone.

**Comment by Prezzodaman** [comment]
I've just committed a huge amount of changes to the main source files (including lots of bug fixes and other changes to the Module object), and with these changes I've also increased the version number.

I successfully made a PyPI account, but before I finally publish Pymod, I just want to make sure I haven't missed anything, so if there's any important changes that need to be made, let me know and I'll merge any necessary pull requests!

**Comment by DidierMalenfant** [comment]
I have a PR relating to #4 but I can update it with your changes down the road.

I'm stuck making a test case for it because it's probably not possible to compare channels mixed in your module and mixed by merging channels afterwards. You have precision internally before you mix the channels that is lost when the file is written out. Still looking for the best way to deal with this on the test's end.

**Comment by Prezzodaman** [comment]
I'm not sure I understand. When you mention "precision", are you talking about the volume of each channel being reduced, or what do you mean exactly?

**Comment by DidierMalenfant** [comment]
Re: changing version numbers for the module, make sure that you stick with [semver](https://semver.org) because some users may rely on that to automatically update the module or not with their project.

Major version changes should only be for changes that are NOT backwards compatible. Some users may prevent major version bumps to avoid breaking their app. If the change doesn't break compatibility then it should be a minor version change so that everyone can automatically update to it. Patch version number should be for bug fixes.

>I'm not sure I understand. When you mention "precision", are you talking about the volume of each channel being reduced, or what do you mean exactly?

I changed the separate channel rendering code so that it honors the stereo/mono modes. Up to now it was only rendering channels in mono.

This makes the code simpler because it removes special code paths for rendering channels. It just uses the same regular rendering and mutes all other channels.

That works fine so I'm building unit tests to make sure that mixing the channels render files by hand produces the same result as rendering everything as one file.

Problem I'm encountering is that some modules (filter.mod for example) end up with an off by 1 error on some samples. This is likely cause by the mixing happening on sample data in one case (which I imagine has more precision to work with) but when I mix the files by hand I'm mixing samples written to the wav files, which have less precision to work with (by 1 bit it seems).

So the one pass render give me a sample of `b4e3` for example, while mixing the same sample from the individual channel renders by hand give me `b4e2`.

I'm having a hard time following the sample value stuff.... there's a lot of +128, +32768 and conversions between signed and unsigned. Did you use a model/doc somewhere to write this? Why not keep everything signed all the way through for example?

**Comment by Prezzodaman** [comment]
Understood, in that case I'll change the version number to 1.1.0 (I thought the entire API rewrite would warrant a version increase, but I guess not). And regarding the channel rendering code, I will merge the pull request you made, as it's a much more sensible way of handing it!

I've never analyzed Pymod's renders in such detail before, so I completely glossed over the "off by one" errors. And since you were wondering, I used one document to refer to the .mod file format, and all the sample maths and conversion is done using existing knowledge. Also, I can't seem to replicate your issue; when I render "filter.mod" to a mixed file, then render it to individual channels, mix the channels together and invert it into the original file, there is complete silence. So I'm not sure what's happening with your version (though it's made me aware of another bug, so thanks for that!)

For reference, the channel bytes are stored as unsigned values between 0 and 65535, and the only other major conversion is when grabbing the appropriate sample byte from the module - it converts the signed byte to unsigned, then takes 128 away to make it a true signed value, THEN divides it by 128 so it can change the volume by multiplying the byte... that's when it's multiplied back up to a 16-bit value, and with 32768 added, the value is between 0 and 65535 again. It also needs to be in that range so the byte can be panned (and that function returns a signed value, which honestly makes less sense!)

Hopefully you understand that explanation, and again, please forgive my ignorance when it comes to testing and things like that! I feel a little dumb when obvious mistakes are pointed out, so I apologize in advance :S

**Comment by DidierMalenfant** [comment]
>Hopefully you understand that explanation, and again, please forgive my ignorance when it comes to testing and things like that! I feel a little dumb when obvious mistakes are pointed out, so I apologize in advance :S

As I contribute more code don't you worry, obvious mistakes from my end are coming too :)

Let's continue the conversation about my testing issue in #16

**Comment by Prezzodaman** [comment]
So... slight issue regarding PyPI. I know Pymod isn't quite ready yet, but I had a look, and there's already a package named "pymod". What package name would work instead? I was thinking something like "pymod-module" or "pymod-amiga" or something to tell it apart...

**Comment by DidierMalenfant** [comment]
Ah crap... I thought I checked that 😂

`pymod-amiga` works I think. We can keep the command line `pymod` but just rename the package. Want me to tackle it?

**Comment by Prezzodaman** [comment]
I'd appreciate that, thank you!

**Comment by DidierMalenfant** [comment]
PR #19 should take care of it.

**Comment by Prezzodaman** [comment]
Pymod is very nearly ready for publishing, but just to double check, should the test files still be bundled in the published package? Is that intentional or not?

**Comment by DidierMalenfant** [comment]
Probably not. I think you're right.

**Comment by Prezzodaman** [comment]
I've removed the test folder from the package! A few more bugfixes and cleanups, and it should be ready for PyPI :)

**Comment by DidierMalenfant** [comment]
Just noticed the ReadMe doesn't seem to have any info on how to use legacy mode.

**Comment by DidierMalenfant** [comment]
Ping! 😉

I'm going to release a first version of my project which uses this. Should I just include it into my module for now or are you close to posting on pypi?

Thanks!

**Comment by Prezzodaman** [comment]
I haven't changed much since the last commit, I'm fairly confident that it's stable enough for release, so I'll try and figure out how to get it published. I'll let you know when that's done, then you can release your project!

**Comment by Prezzodaman** [comment]
It should be published now! Hopefully it works okay!

**Comment by DidierMalenfant** [comment]
Sweet!
