### ISSUE TITLE
Unit tests for test modules

### ISSUE THREAD

**Issue by DidierMalenfant** [Prezzodaman/pymod#5]
The test modules added in the repo are great. It could be useful to check in renders of those modules and build unit tests that check that these remain correct after changes are made to the code.

I can provide a PR for this.

**Comment by Prezzodaman** [comment]
This is a very good idea! Let me know how we can go about this (I've never actually done something like this before) and I can get some renders done in Pymod's current state.

**Comment by DidierMalenfant** [comment]
Let me do the module part #3 first and we can add the unit tests on top of that.

**Comment by DidierMalenfant** [comment]
I've got unit tests working are ready to be submitted bu they rely on #6 so I will wait for that to be merged before creating a new PR.

**Comment by DidierMalenfant** [comment]
Ok #9 has the unit testing plugged in. Let me know if it works for you.
